### ISSUE TITLE
Incorrect linting of dictionaries with string keys

### ISSUE THREAD

**Issue by asltpo** [paulober/Pico-W-Stub#13]
**Describe the bug**
Steps:
1. Start VSCode
2. Create a new project and configure it as a MicroPico project using MicroPico > Configure Project
3. Create a new Python file and create a dictionary object with a string key (example code below).

Expected behaviour:
No warnings or errors.

Actual behaviour:
Pylance reports the following error:

```
Dictionary key must be hashable
  Type "Literal['key1']" is not hashable Pylance(reportGeneralTypeIssues)
```

**Notes:**

The expected behaviour is restored if:
- the project has not been configured as a MicroPico project
- Pylance is backdated to v2023.8.30 or older

**Code or Screenshots**

Python code:

`my_dict = {"key1": 1}`

**Version info**
VSCode v1.82.2
Pylance v2023.9.20
MicroPico v3.2.5

**Comment by MG-LSJ** [comment]
Having the same issues.

doing this fixes it:
Adding
```py
    def __hash__(self) -> int: ...
```
to the end of class int (and class str) in stdlib -> builtins.pyi removed the warnings from pylance.

https://github.com/Josverl/micropython-stubs/issues/723#issuecomment-1703723773

**Comment by bernd-o-mat** [comment]
Same Pylance behaviour to me.
False positive. "Dictionary key must be hashable..."

**Comment by Snipeye** [comment]
New to uPy, but I'm glad I found this - updating the stdlib buildints.pyi fixed it for now but I'll have to do that for any class I want to use as a dictionary key to avoid squiggles.

Just adding my $0.02 to request a please fix!

**Comment by paulober** [comment]
Expect a fix in the next few hours...

**Comment by paulober** [comment]
@Snipeye @asltpo does https://github.com/paulober/MicroPico/releases/tag/v3.4.0 fix your issues? (it's only MicroPython v1.20.0 but v1.21.0 will follow in the next few days)

**Comment by Snipeye** [comment]
After updating I no longer see the squiggles, and my builtins.pyi was updated. (That is to say: I don't think it was just a holdover from my kludges last night).  Thanks, @paulober !

**Comment by asltpo** [comment]
Ditto, if I follow the steps from my original post but using:

VSCode v1.83.1
Pylance v2023.10.30
MicroPico v3.4.0

I get the correct behaviour.

Many thanks!
