### ISSUE TITLE
Timer constructor does not have freq kwarg

### ISSUE THREAD

**Issue by asasine** [paulober/Pico-W-Stub#2]
MicroPython's `machine.Timer` documents the [constructor arguments](https://docs.micropython.org/en/latest/library/machine.Timer.html#machine.Timer) as matching the [`Timer.init`](https://docs.micropython.org/en/latest/library/machine.Timer.html#machine.Timer.init) function. The `init` function has a `freq: float|None = None` argument, however the stub `Timer.__init__` does not. This causes linting errors when using the constructor form.

![image](https://user-images.githubusercontent.com/5421969/218266975-0e49e3e4-835c-42dc-9222-5149be411686.png)

This linting error does not appear when using the `init` form

![image](https://user-images.githubusercontent.com/5421969/218267032-fc3aa89e-9f8b-4925-b546-9de5843743f8.png)

---
I went to see if I could add the additional arg to the stub but got lost discerning between /dist, /frozen, and /generated, and where I should add to. Do you have a CONTRIBUTING.md in the works?

**Comment by paulober** [comment]
Thanks for reporting the issue.
You can find details about the folder structure in the [readme](https://github.com/paulober/Pico-W-Stub#about-the-stubs).
But you're right a CONTRIBUTING.md would be a good idee if more people start opening prs...

In short: You can make changes in the /frozen folder, then run the post-process python script in the project root to reflect the changes in the dist output directory.
