### ISSUE TITLE
SoftI2C is asking for an id parameter and it should not

### ISSUE THREAD

**Issue by couillonnade** [paulober/Pico-W-Stub#4]
SoftI2C stub is asking for an id parameter. This only exists for hardware I2C.

This is correct:
`t = machine.SoftI2C(scl=machine.Pin(4),sda=machine.Pin(5),freq=400000)`

This is incorrect:

```
t = machine.SoftI2C(0,scl=machine.Pin(4),sda=machine.Pin(5),freq=400000)

Traceback (most recent call last):
File "", line 1, in 
TypeError: extra keyword arguments given
```

Pylance is not happy with it:

```
i2c = machine.SoftI2C(scl=machine.Pin(sclpin),
sda=machine.Pin(sdapin),
freq=i2cfreq)

Expected 1 more positional argumentPylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
(module) machine
```

It seems that this has changed in v1.14 in 2021 so this is quite old since the latest is 1.19
https://github.com/micropython/micropython/releases

Breaking changes in this release are:
machine.I2C and machine.SPI constructors are changed when using software-based I2C and SPI. Code that constructed I2C/SPI peripherals in the following way will need to be changed (or else their use will emit a warning which will eventually be an error):

machine.I2C(-1, ...) -> machine.SoftI2C(...)
machine.I2C(scl=scl, sda=sda) -> machine.SoftI2C(scl=scl, sda=sda)

machine.SPI(-1, ...) -> machine.SoftSPI(...)
machine.SPI(sck=sck, mosi=mosi, miso=miso)
-> machine.SoftSPI(sck=sck, mosi=mosi, miso=miso)

**Comment by paulober** [comment]
Thanks for reporting, will be fixed with next release...

**Comment by couillonnade** [comment]
Thank you! While you are at it, I also found that hardware timers do not accept freq parameter 

Timer(freq= ...)

Here is my fix in machine.py

```
def __init__(
        self,
        id: int|None=None,
        /,
        *,
        freq: float|None = None,
        mode: int = PERIODIC,
        period: int = -1,
        callback: Callable[["Timer"], None] |None = None,
    )
```

I've seen that in few places the constructor (__init__) is different from the init() method below. Not sure why?

**Comment by paulober** [comment]
@couillonnade Thanks for also reporting this issue. Will be fixed it in an upcoming patch.

That's because the project is originally based on a unmaintained fork which for some reason just put together random source and different stuff wich lead to some issues with the current state. With reports like this i'll try to fix all of this stuff up over time and keep it better updated with new firmware updates.

**Comment by couillonnade** [comment]
@paulober. I will try to make a PR next time but I need to understand more the way it is organized!

You might also know that there is this interesting repo : https://github.com/Josverl/micropython-stubber and all stubs available here: https://github.com/Josverl/micropython-stubs/tree/main/stubs 

Not sure if there is a way to compare to check any discrepancies. 

I am using Pico-W-Stub because of ease of deploy, init project, pin out documentation, etc... but I hear good feedback about the work done with Josverl!
