### ISSUE TITLE
Update to micropython v1.20.0 (Stable)

### ISSUE THREAD

**Issue by YUKI2eN3e** [paulober/Pico-W-Stub#6]
Update to micropython v1.20.0 (Stable).

Since there is now a stable micropython for Pico W it's probably best to use it instead of the unstable releases.

Switch to [micropython v1.20.0](https://github.com/micropython/micropython/releases/tag/v1.20.0) or newer.

**Comment by paulober** [comment]
`v1.20.0` hasn't changed anything (from a stub perspective). But i'll bump the version number...

**Comment by couillonnade** [comment]
What is the workflow to update stubs on an existing project? Re-run "configure project"?

**Comment by paulober** [comment]
@couillonnade It auto-updates the stubs for all projects system wide  when running the updated version of the extension the first time.
